In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandasgui import show

Import datafile for analysis

First: import data and check everything is in a decent format.

In this case:

imported dataset;

delimited by semicolon;

encoding: to understand french letters;

on bad lines: "skip", skip wrong formatted lines, not really relevant in our dataset;

engine: "python" tell which engine chosen to parse, not really necessary now


#show(data)= this open a web window with all data in nice table format. 
Useful since I cant see the whole database preview on Jupyter

In [17]:
data = pd.read_csv(
     "SNCF_dataset.csv",   
    sep=';',                   # semikolon-separerad
    encoding='utf-8-sig',      # för franska tecken så det inte blir konstigt
    #on_bad_lines='skip',       # hoppar över rader som är helt trasiga      
    #engine = 'python'          # för att hantera inbäddade semikolon
)


#show(data)                    #OBS pandasgui, öppnas separat
data.head(5)

,Date,Service,Gare de départ,Gare d'arrivée,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,...,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
0,2018-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141,870,5,NaN,289,11.247809,...,110,6.511118,44,8,36.134454,31.092437,10.924370,15.966387,5.042017,0.840336
1,2018-01,National,LA ROCHELLE VILLE,PARIS MONTPARNASSE,165,222,0,NaN,8,2.875000,...,22,5.696096,5,0,15.384615,30.769231,38.461538,11.538462,3.846154,0.000000
2,2018-01,National,PARIS MONTPARNASSE,QUIMPER,220,248,1,NaN,37,9.501351,...,26,7.548387,17,7,26.923077,38.461538,15.384615,19.230769,0.000000,0.000000
3,2018-01,National,PARIS MONTPARNASSE,ST MALO,156,102,0,NaN,12,19.912500,...,8,6.724757,6,4,23.076923,46.153846,7.692308,15.384615,7.692308,0.000000
4,2018-01,National,PARIS MONTPARNASSE,ST PIERRE DES CORPS,61,391,2,NaN,61,7.796995,...,17,3.346487,6,0,21.212121,42.424242,9.090909,21.212121,6.060606,0.000000

Sort my database: 
1. only National service and Delays cause by rollings stocks/infrastructure in 2023


"Un train est considéré à l'heure si son retard au terminus est inférieur à 5min pour un parcours inférieur à 1h30

Un train est considéré à l'heure si son retard au terminus est inférieur à 10min pour un parcours entre 1h30 et 3h

Un train est considéré à l'heure si son retard au terminus est inférieur à 15min pour un parcours au-delà de 3h"

In [ ]:
national_data = data[(data['Service'] == 'National') & (data['Date'].str.startswith('2023'))]       #choose only National trains ad year=2023
columns_to_drop = [       'Service',                                #working on delays caused by infrastructure/rolling stocks, drop everything else
                   'Commentaire annulations', 
                   'Commentaire retards au départ', 
                   'Commentaire retards à l\'arrivée',
                   'Nombre de trains en retard au départ',
                   'Nombre de trains en retard à l\'arrivée',
                   'Retard moyen trains en retard > 15 (si liaison concurrencée par vol)',
                   'Retard moyen des trains en retard au départ',
                   'Retard moyen de tous les trains au départ',
                   'Retard moyen de tous les trains à l\'arrivée',
                   'Retard moyen des trains en retard à l\'arrivée',
                   'Prct retard pour causes externes',
                   'Prct retard pour cause gestion trafic',
                   'Prct retard pour cause gestion en gare et réutilisation de matériel',
                   'Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)',
          ]

   #get only to decimals in the last two columns

nationaltrains_data_1 = national_data.drop(columns=columns_to_drop).copy()
columns_to_format = [
    'Prct retard pour cause infrastructure',
    'Prct retard pour cause matériel roulant'
]
nationaltrains_data_1[columns_to_format] = nationaltrains_data_1[columns_to_format].round(2)

#print(nationaltrains_data_1.columns)

display(nationaltrains_data_1.head(10))    #use display instead of print to get a nice table view!

,Date,Gare de départ,Gare d'arrivée,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Nombre trains en retard > 15min,Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour cause infrastructure,Prct retard pour cause matériel roulant
7430,2023-01,BORDEAUX ST JEAN,PARIS MONTPARNASSE,140,1075,66,115,60,28,27.54,11.59
7431,2023-01,CHAMBERY CHALLES LES EAUX,PARIS LYON,180,334,16,64,19,6,29.58,2.82
7432,2023-01,MACON LOCHE,PARIS LYON,99,252,15,59,16,3,24.64,5.80
7433,2023-01,METZ,PARIS EST,89,310,18,25,15,6,9.09,20.45
7434,2023-01,MONTPELLIER,PARIS LYON,212,249,7,28,10,4,28.57,25.00
7435,2023-01,PARIS EST,METZ,86,277,16,25,17,6,9.76,21.95
7436,2023-01,PARIS LYON,AIX EN PROVENCE TGV,187,461,18,39,19,3,15.00,22.50
7437,2023-01,PARIS LYON,ANNECY,229,154,8,24,11,0,16.67,37.50
7438,2023-01,PARIS LYON,NICE VILLE,353,225,6,34,14,6,38.24,8.82
7439,2023-01,PARIS MONTPARNASSE,ANGOULEME,122,304,26,18,10,5,29.03,19.35

Saved view as new dataset: Delays in 2023 cause by Infrastructure / rolling stocks

In [47]:
nationaltrains_data_1.to_csv("Delays_Infr_RStocks_2023.csv", index=False, sep=';')